spring:
  datasource:
    url: jdbc:h2:mem:example
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
